// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file soccerbuddy/club/v1/club_service.proto (package soccerbuddy.club.v1, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc, serviceDesc, } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
/**
 * Describes the file soccerbuddy/club/v1/club_service.proto.
 */
export const file_soccerbuddy_club_v1_club_service = 
/*@__PURE__*/
fileDesc("CiZzb2NjZXJidWRkeS9jbHViL3YxL2NsdWJfc2VydmljZS5wcm90bxITc29jY2VyYnVkZHkuY2x1Yi52MSIhChFDcmVhdGVDbHViUmVxdWVzdBIMCgRuYW1lGAEgASgJIjwKEkNyZWF0ZUNsdWJSZXNwb25zZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEgwKBHNsdWcYAyABKAkiJAoUR2V0Q2x1YkJ5U2x1Z1JlcXVlc3QSDAoEc2x1ZxgBIAEoCSKfAQoVR2V0Q2x1YkJ5U2x1Z1Jlc3BvbnNlEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSDAoEc2x1ZxgDIAEoCRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcDLYAQoLQ2x1YlNlcnZpY2USXwoKQ3JlYXRlQ2x1YhImLnNvY2NlcmJ1ZGR5LmNsdWIudjEuQ3JlYXRlQ2x1YlJlcXVlc3QaJy5zb2NjZXJidWRkeS5jbHViLnYxLkNyZWF0ZUNsdWJSZXNwb25zZSIAEmgKDUdldENsdWJCeVNsdWcSKS5zb2NjZXJidWRkeS5jbHViLnYxLkdldENsdWJCeVNsdWdSZXF1ZXN0Giouc29jY2VyYnVkZHkuY2x1Yi52MS5HZXRDbHViQnlTbHVnUmVzcG9uc2UiAELaAQoXY29tLnNvY2NlcmJ1ZGR5LmNsdWIudjFCEENsdWJTZXJ2aWNlUHJvdG9QAVo/Z2l0aHViLmNvbS9yc21pZHQvc29jY2VyYnVkZHkvZ2VuL2dvL3NvY2NlcmJ1ZGR5L2NsdWIvdjE7Y2x1YnYxogIDU0NYqgITU29jY2VyYnVkZHkuQ2x1Yi5WMcoCE1NvY2NlcmJ1ZGR5XENsdWJcVjHiAh9Tb2NjZXJidWRkeVxDbHViXFYxXEdQQk1ldGFkYXRh6gIVU29jY2VyYnVkZHk6OkNsdWI6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);
/**
 * Describes the message soccerbuddy.club.v1.CreateClubRequest.
 * Use `create(CreateClubRequestSchema)` to create a new message.
 */
export const CreateClubRequestSchema = 
/*@__PURE__*/
messageDesc(file_soccerbuddy_club_v1_club_service, 0);
/**
 * Describes the message soccerbuddy.club.v1.CreateClubResponse.
 * Use `create(CreateClubResponseSchema)` to create a new message.
 */
export const CreateClubResponseSchema = 
/*@__PURE__*/
messageDesc(file_soccerbuddy_club_v1_club_service, 1);
/**
 * Describes the message soccerbuddy.club.v1.GetClubBySlugRequest.
 * Use `create(GetClubBySlugRequestSchema)` to create a new message.
 */
export const GetClubBySlugRequestSchema = 
/*@__PURE__*/
messageDesc(file_soccerbuddy_club_v1_club_service, 2);
/**
 * Describes the message soccerbuddy.club.v1.GetClubBySlugResponse.
 * Use `create(GetClubBySlugResponseSchema)` to create a new message.
 */
export const GetClubBySlugResponseSchema = 
/*@__PURE__*/
messageDesc(file_soccerbuddy_club_v1_club_service, 3);
/**
 * @generated from service soccerbuddy.club.v1.ClubService
 */
export const ClubService = /*@__PURE__*/ serviceDesc(file_soccerbuddy_club_v1_club_service, 0);
