// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file soccerbuddy/shared.proto (package soccerbuddy.shared, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file soccerbuddy/shared.proto.
 */
export const file_soccerbuddy_shared: GenFile = /*@__PURE__*/
  fileDesc("Chhzb2NjZXJidWRkeS9zaGFyZWQucHJvdG8SEnNvY2NlcmJ1ZGR5LnNoYXJlZCIoCiZMb2dpbk9yQWNjb3VudENyZWF0aW9uUmVxdWlyZWRSZXNwb25zZSIeChxBY2NvdW50QWxyZWFkeUxpbmtlZFRvUGVyc29uKlIKC0FjY291bnRMaW5rEhkKFUxJTktFRF9BU19VTlNQRUNJRklFRBAAEhIKDkxJTktFRF9BU19TRUxGEAESFAoQTElOS0VEX0FTX1BBUkVOVBACKoEBCgxSYXRpbmdQb2xpY3kSHQoZUkFUSU5HX1BPTElDWV9VTlNQRUNJRklFRBAAEhsKF1JBVElOR19QT0xJQ1lfRk9SQklEREVOEAESGQoVUkFUSU5HX1BPTElDWV9BTExPV0VEEAISGgoWUkFUSU5HX1BPTElDWV9SRVFVSVJFRBADQsABChZjb20uc29jY2VyYnVkZHkuc2hhcmVkQgtTaGFyZWRQcm90b1ABWjBnaXRodWIuY29tL3JzbWlkdC9zb2NjZXJidWRkeS9nZW4vZ28vc29jY2VyYnVkZHmiAgNTU1iqAhJTb2NjZXJidWRkeS5TaGFyZWTKAhJTb2NjZXJidWRkeVxTaGFyZWTiAh5Tb2NjZXJidWRkeVxTaGFyZWRcR1BCTWV0YWRhdGHqAhNTb2NjZXJidWRkeTo6U2hhcmVkYgZwcm90bzM");

/**
 * @generated from message soccerbuddy.shared.LoginOrAccountCreationRequiredResponse
 */
export type LoginOrAccountCreationRequiredResponse = Message<"soccerbuddy.shared.LoginOrAccountCreationRequiredResponse"> & {
};

/**
 * Describes the message soccerbuddy.shared.LoginOrAccountCreationRequiredResponse.
 * Use `create(LoginOrAccountCreationRequiredResponseSchema)` to create a new message.
 */
export const LoginOrAccountCreationRequiredResponseSchema: GenMessage<LoginOrAccountCreationRequiredResponse> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_shared, 0);

/**
 * @generated from message soccerbuddy.shared.AccountAlreadyLinkedToPerson
 */
export type AccountAlreadyLinkedToPerson = Message<"soccerbuddy.shared.AccountAlreadyLinkedToPerson"> & {
};

/**
 * Describes the message soccerbuddy.shared.AccountAlreadyLinkedToPerson.
 * Use `create(AccountAlreadyLinkedToPersonSchema)` to create a new message.
 */
export const AccountAlreadyLinkedToPersonSchema: GenMessage<AccountAlreadyLinkedToPerson> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_shared, 1);

/**
 * @generated from enum soccerbuddy.shared.AccountLink
 */
export enum AccountLink {
  /**
   * @generated from enum value: LINKED_AS_UNSPECIFIED = 0;
   */
  LINKED_AS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: LINKED_AS_SELF = 1;
   */
  LINKED_AS_SELF = 1,

  /**
   * @generated from enum value: LINKED_AS_PARENT = 2;
   */
  LINKED_AS_PARENT = 2,
}

/**
 * Describes the enum soccerbuddy.shared.AccountLink.
 */
export const AccountLinkSchema: GenEnum<AccountLink> = /*@__PURE__*/
  enumDesc(file_soccerbuddy_shared, 0);

/**
 * @generated from enum soccerbuddy.shared.RatingPolicy
 */
export enum RatingPolicy {
  /**
   * @generated from enum value: RATING_POLICY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RATING_POLICY_FORBIDDEN = 1;
   */
  FORBIDDEN = 1,

  /**
   * @generated from enum value: RATING_POLICY_ALLOWED = 2;
   */
  ALLOWED = 2,

  /**
   * @generated from enum value: RATING_POLICY_REQUIRED = 3;
   */
  REQUIRED = 3,
}

/**
 * Describes the enum soccerbuddy.shared.RatingPolicy.
 */
export const RatingPolicySchema: GenEnum<RatingPolicy> = /*@__PURE__*/
  enumDesc(file_soccerbuddy_shared, 1);

