// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file soccerbuddy/shared.proto (package succerbuddy.shared, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv1";
import { fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file soccerbuddy/shared.proto.
 */
export const file_soccerbuddy_shared: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Chhzb2NjZXJidWRkeS9zaGFyZWQucHJvdG8SEnN1Y2NlcmJ1ZGR5LnNoYXJlZELAAQoWY29tLnN1Y2NlcmJ1ZGR5LnNoYXJlZEILU2hhcmVkUHJvdG9QAVowZ2l0aHViLmNvbS9yc21pZHQvc29jY2VyYnVkZHkvZ2VuL2dvL3NvY2NlcmJ1ZGR5ogIDU1NYqgISU3VjY2VyYnVkZHkuU2hhcmVkygISU3VjY2VyYnVkZHlcU2hhcmVk4gIeU3VjY2VyYnVkZHlcU2hhcmVkXEdQQk1ldGFkYXRh6gITU3VjY2VyYnVkZHk6OlNoYXJlZGIGcHJvdG8z",
  );
