host = "localhost:4488"

[EventJournal]
[EventJournal.PG]
host = "localhost:34343"
user = "soccerbuddy"
password = "soccerbuddy"
name = "soccerbuddy"

[EventJournal.Redis]
host = "localhost:6379"

[Permify]
host = "localhost:3478"

[Setup]
root.email = "test@example.com"
root.password = "password"
root.firstName = "Joe"
root.lastName = "Doe"
