// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file soccerbuddy/person/v1/errors.proto (package soccerbuddy.person.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file soccerbuddy/person/v1/errors.proto.
 */
export const file_soccerbuddy_person_v1_errors: GenFile = /*@__PURE__*/
  fileDesc("CiJzb2NjZXJidWRkeS9wZXJzb24vdjEvZXJyb3JzLnByb3RvEhVzb2NjZXJidWRkeS5wZXJzb24udjEiHgocTG9naW5PclJlZ2lzdGVyUmVxdWlyZWRFcnJvciIjCiFBY2NvdW50QWxyZWFkeUxpbmtlZFRvUGVyc29uRXJyb3IiGgoYVG9vTWFueUxpbmtzQ3JlYXRlZEVycm9yQuMBChljb20uc29jY2VyYnVkZHkucGVyc29uLnYxQgtFcnJvcnNQcm90b1ABWkNnaXRodWIuY29tL3JzbWlkdC9zb2NjZXJidWRkeS9nZW4vZ28vc29jY2VyYnVkZHkvcGVyc29uL3YxO3BlcnNvbnYxogIDU1BYqgIVU29jY2VyYnVkZHkuUGVyc29uLlYxygIVU29jY2VyYnVkZHlcUGVyc29uXFYx4gIhU29jY2VyYnVkZHlcUGVyc29uXFYxXEdQQk1ldGFkYXRh6gIXU29jY2VyYnVkZHk6OlBlcnNvbjo6VjFiBnByb3RvMw");

/**
 * @generated from message soccerbuddy.person.v1.LoginOrRegisterRequiredError
 */
export type LoginOrRegisterRequiredError = Message<"soccerbuddy.person.v1.LoginOrRegisterRequiredError"> & {
};

/**
 * Describes the message soccerbuddy.person.v1.LoginOrRegisterRequiredError.
 * Use `create(LoginOrRegisterRequiredErrorSchema)` to create a new message.
 */
export const LoginOrRegisterRequiredErrorSchema: GenMessage<LoginOrRegisterRequiredError> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_person_v1_errors, 0);

/**
 * @generated from message soccerbuddy.person.v1.AccountAlreadyLinkedToPersonError
 */
export type AccountAlreadyLinkedToPersonError = Message<"soccerbuddy.person.v1.AccountAlreadyLinkedToPersonError"> & {
};

/**
 * Describes the message soccerbuddy.person.v1.AccountAlreadyLinkedToPersonError.
 * Use `create(AccountAlreadyLinkedToPersonErrorSchema)` to create a new message.
 */
export const AccountAlreadyLinkedToPersonErrorSchema: GenMessage<AccountAlreadyLinkedToPersonError> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_person_v1_errors, 1);

/**
 * @generated from message soccerbuddy.person.v1.TooManyLinksCreatedError
 */
export type TooManyLinksCreatedError = Message<"soccerbuddy.person.v1.TooManyLinksCreatedError"> & {
};

/**
 * Describes the message soccerbuddy.person.v1.TooManyLinksCreatedError.
 * Use `create(TooManyLinksCreatedErrorSchema)` to create a new message.
 */
export const TooManyLinksCreatedErrorSchema: GenMessage<TooManyLinksCreatedError> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_person_v1_errors, 2);

