// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file soccerbuddy/club/v1/club_service.proto (package soccerbuddy.club.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file soccerbuddy/club/v1/club_service.proto.
 */
export const file_soccerbuddy_club_v1_club_service: GenFile = /*@__PURE__*/
  fileDesc("CiZzb2NjZXJidWRkeS9jbHViL3YxL2NsdWJfc2VydmljZS5wcm90bxITc29jY2VyYnVkZHkuY2x1Yi52MSIhChFDcmVhdGVDbHViUmVxdWVzdBIMCgRuYW1lGAEgASgJIjwKEkNyZWF0ZUNsdWJSZXNwb25zZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEgwKBHNsdWcYAyABKAkiJAoUR2V0Q2x1YkJ5U2x1Z1JlcXVlc3QSDAoEc2x1ZxgBIAEoCSKfAQoVR2V0Q2x1YkJ5U2x1Z1Jlc3BvbnNlEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSDAoEc2x1ZxgDIAEoCRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCISChBMaXN0Q2x1YnNSZXF1ZXN0IuABChFMaXN0Q2x1YnNSZXNwb25zZRI6CgVjbHVicxgBIAMoCzIrLnNvY2NlcmJ1ZGR5LmNsdWIudjEuTGlzdENsdWJzUmVzcG9uc2UuQ2x1YhqOAQoEQ2x1YhIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEgwKBHNsdWcYAyABKAkSLgoKY3JlYXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiQAoZUHJvbW90ZVVzZXJUb0FkbWluUmVxdWVzdBIPCgdjbHViX2lkGAEgASgJEhIKCmFjY291bnRfaWQYAiABKAkiHAoaUHJvbW90ZVVzZXJUb0FkbWluUmVzcG9uc2UyrwMKC0NsdWJTZXJ2aWNlEl8KCkNyZWF0ZUNsdWISJi5zb2NjZXJidWRkeS5jbHViLnYxLkNyZWF0ZUNsdWJSZXF1ZXN0Gicuc29jY2VyYnVkZHkuY2x1Yi52MS5DcmVhdGVDbHViUmVzcG9uc2UiABJoCg1HZXRDbHViQnlTbHVnEikuc29jY2VyYnVkZHkuY2x1Yi52MS5HZXRDbHViQnlTbHVnUmVxdWVzdBoqLnNvY2NlcmJ1ZGR5LmNsdWIudjEuR2V0Q2x1YkJ5U2x1Z1Jlc3BvbnNlIgASXAoJTGlzdENsdWJzEiUuc29jY2VyYnVkZHkuY2x1Yi52MS5MaXN0Q2x1YnNSZXF1ZXN0GiYuc29jY2VyYnVkZHkuY2x1Yi52MS5MaXN0Q2x1YnNSZXNwb25zZSIAEncKElByb21vdGVVc2VyVG9BZG1pbhIuLnNvY2NlcmJ1ZGR5LmNsdWIudjEuUHJvbW90ZVVzZXJUb0FkbWluUmVxdWVzdBovLnNvY2NlcmJ1ZGR5LmNsdWIudjEuUHJvbW90ZVVzZXJUb0FkbWluUmVzcG9uc2UiAELaAQoXY29tLnNvY2NlcmJ1ZGR5LmNsdWIudjFCEENsdWJTZXJ2aWNlUHJvdG9QAVo/Z2l0aHViLmNvbS9yc21pZHQvc29jY2VyYnVkZHkvZ2VuL2dvL3NvY2NlcmJ1ZGR5L2NsdWIvdjE7Y2x1YnYxogIDU0NYqgITU29jY2VyYnVkZHkuQ2x1Yi5WMcoCE1NvY2NlcmJ1ZGR5XENsdWJcVjHiAh9Tb2NjZXJidWRkeVxDbHViXFYxXEdQQk1ldGFkYXRh6gIVU29jY2VyYnVkZHk6OkNsdWI6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message soccerbuddy.club.v1.CreateClubRequest
 */
export type CreateClubRequest = Message<"soccerbuddy.club.v1.CreateClubRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message soccerbuddy.club.v1.CreateClubRequest.
 * Use `create(CreateClubRequestSchema)` to create a new message.
 */
export const CreateClubRequestSchema: GenMessage<CreateClubRequest> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 0);

/**
 * @generated from message soccerbuddy.club.v1.CreateClubResponse
 */
export type CreateClubResponse = Message<"soccerbuddy.club.v1.CreateClubResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string slug = 3;
   */
  slug: string;
};

/**
 * Describes the message soccerbuddy.club.v1.CreateClubResponse.
 * Use `create(CreateClubResponseSchema)` to create a new message.
 */
export const CreateClubResponseSchema: GenMessage<CreateClubResponse> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 1);

/**
 * @generated from message soccerbuddy.club.v1.GetClubBySlugRequest
 */
export type GetClubBySlugRequest = Message<"soccerbuddy.club.v1.GetClubBySlugRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;
};

/**
 * Describes the message soccerbuddy.club.v1.GetClubBySlugRequest.
 * Use `create(GetClubBySlugRequestSchema)` to create a new message.
 */
export const GetClubBySlugRequestSchema: GenMessage<GetClubBySlugRequest> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 2);

/**
 * @generated from message soccerbuddy.club.v1.GetClubBySlugResponse
 */
export type GetClubBySlugResponse = Message<"soccerbuddy.club.v1.GetClubBySlugResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string slug = 3;
   */
  slug: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message soccerbuddy.club.v1.GetClubBySlugResponse.
 * Use `create(GetClubBySlugResponseSchema)` to create a new message.
 */
export const GetClubBySlugResponseSchema: GenMessage<GetClubBySlugResponse> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 3);

/**
 * @generated from message soccerbuddy.club.v1.ListClubsRequest
 */
export type ListClubsRequest = Message<"soccerbuddy.club.v1.ListClubsRequest"> & {
};

/**
 * Describes the message soccerbuddy.club.v1.ListClubsRequest.
 * Use `create(ListClubsRequestSchema)` to create a new message.
 */
export const ListClubsRequestSchema: GenMessage<ListClubsRequest> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 4);

/**
 * @generated from message soccerbuddy.club.v1.ListClubsResponse
 */
export type ListClubsResponse = Message<"soccerbuddy.club.v1.ListClubsResponse"> & {
  /**
   * @generated from field: repeated soccerbuddy.club.v1.ListClubsResponse.Club clubs = 1;
   */
  clubs: ListClubsResponse_Club[];
};

/**
 * Describes the message soccerbuddy.club.v1.ListClubsResponse.
 * Use `create(ListClubsResponseSchema)` to create a new message.
 */
export const ListClubsResponseSchema: GenMessage<ListClubsResponse> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 5);

/**
 * @generated from message soccerbuddy.club.v1.ListClubsResponse.Club
 */
export type ListClubsResponse_Club = Message<"soccerbuddy.club.v1.ListClubsResponse.Club"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string slug = 3;
   */
  slug: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message soccerbuddy.club.v1.ListClubsResponse.Club.
 * Use `create(ListClubsResponse_ClubSchema)` to create a new message.
 */
export const ListClubsResponse_ClubSchema: GenMessage<ListClubsResponse_Club> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 5, 0);

/**
 * @generated from message soccerbuddy.club.v1.PromoteUserToAdminRequest
 */
export type PromoteUserToAdminRequest = Message<"soccerbuddy.club.v1.PromoteUserToAdminRequest"> & {
  /**
   * @generated from field: string club_id = 1;
   */
  clubId: string;

  /**
   * @generated from field: string account_id = 2;
   */
  accountId: string;
};

/**
 * Describes the message soccerbuddy.club.v1.PromoteUserToAdminRequest.
 * Use `create(PromoteUserToAdminRequestSchema)` to create a new message.
 */
export const PromoteUserToAdminRequestSchema: GenMessage<PromoteUserToAdminRequest> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 6);

/**
 * @generated from message soccerbuddy.club.v1.PromoteUserToAdminResponse
 */
export type PromoteUserToAdminResponse = Message<"soccerbuddy.club.v1.PromoteUserToAdminResponse"> & {
};

/**
 * Describes the message soccerbuddy.club.v1.PromoteUserToAdminResponse.
 * Use `create(PromoteUserToAdminResponseSchema)` to create a new message.
 */
export const PromoteUserToAdminResponseSchema: GenMessage<PromoteUserToAdminResponse> = /*@__PURE__*/
  messageDesc(file_soccerbuddy_club_v1_club_service, 7);

/**
 * @generated from service soccerbuddy.club.v1.ClubService
 */
export const ClubService: GenService<{
  /**
   * @generated from rpc soccerbuddy.club.v1.ClubService.CreateClub
   */
  createClub: {
    methodKind: "unary";
    input: typeof CreateClubRequestSchema;
    output: typeof CreateClubResponseSchema;
  },
  /**
   * @generated from rpc soccerbuddy.club.v1.ClubService.GetClubBySlug
   */
  getClubBySlug: {
    methodKind: "unary";
    input: typeof GetClubBySlugRequestSchema;
    output: typeof GetClubBySlugResponseSchema;
  },
  /**
   * @generated from rpc soccerbuddy.club.v1.ClubService.ListClubs
   */
  listClubs: {
    methodKind: "unary";
    input: typeof ListClubsRequestSchema;
    output: typeof ListClubsResponseSchema;
  },
  /**
   * @generated from rpc soccerbuddy.club.v1.ClubService.PromoteUserToAdmin
   */
  promoteUserToAdmin: {
    methodKind: "unary";
    input: typeof PromoteUserToAdminRequestSchema;
    output: typeof PromoteUserToAdminResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_soccerbuddy_club_v1_club_service, 0);

